version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d  # Para datos de prueba
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app_network

  api:
    build: .
    container_name: spring_api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URI: jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: com.mysql.cj.jdbc.Driver
    ports:
      - "${API_PORT}:8080"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
    driver: bridge